### ISSUE TITLE
Doesn't support emails which have a dot in them

### ISSUE THREAD

**Issue by aakashpothepalli** [Hamad-Anwar/Task-Sync-Pro-V2#1]
I'm trying to log in with google with my email `p.saiaakash518@gmail.com`, but the app won't let me so.
Here's the error message
```I/flutter (22335): com.google.firebase.database.DatabaseException: Invalid Firebase Database path: Accounts/p.saiaakash518. Firebase Database paths must not contain '.', '#', '$', '[', or ']'
I/flutter (22335):      at com.google.firebase.database.core.utilities.Validation.validatePathString(Validation.java:45)
I/flutter (22335):      at com.google.firebase.database.core.utilities.Validation.validateRootPathString(Validation.java:58)
I/flutter (22335):      at com.google.firebase.database.FirebaseDatabase.getReference(FirebaseDatabase.java:181)
I/flutter (22335):      at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin.getReference(FirebaseDatabasePlugin.java:134)
I/flutter (22335):      at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin.lambda$setValue$3$io-flutter-plugins-firebase-database-FirebaseDatabasePlugin(FirebaseDatabasePlugin.java:206)
I/flutter (22335):      at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin$$ExternalSyntheticLambda13.run(Unknown Source:6)
I/flutter (22335):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPo
D/EGL_emulation(22335): app_time_stats: avg=1045.66ms min=1045.66ms max=1045.66ms count=1
D/EGL_emulation(22335): app_time_stats: avg=3.02ms min=1.88ms max=7.82ms count=61```

**Comment by Hamad-Anwar** [comment]
your email should not contain any special character

**Comment by aakashpothepalli** [comment]
Sure
It's better if it's communicated in the app then. Also users like me, who have a special character wouldn't be able to even login.

**Comment by Hamad-Anwar** [comment]
sure I'll fix it

**Comment by aakashpothepalli** [comment]
Thanks for the amazing app!
I was extensively looking for an app which can do ToDo with Day list view. Tried many and none worked except yours. The code quality also seems great, thanks

**Comment by Hamad-Anwar** [comment]
Glad to hear it! thanks
